name: Validate JSON

on:
  pull_request:
    paths:
      - 'ModConfigs/**/**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install -g ajv-cli

    - name: Validate JSON
      run: |
        if jq 'if .[0].mods and .[0].desc and .[0].name and .[0].authors then true else false end' ${{ github.workspace }}/ModConfigs/**/**/*.json | grep -q true; then
          echo "The JSON file is valid and contains the required parameters."
        else
          echo "The JSON file is invalid or missing required parameters."
          exit 1

        # Check if any files failed the validation
        if [ $? -eq 0 ]; then
          echo "All JSON files passed validation."
        else
          echo "Some JSON files failed validation."
          exit 1
        fi
