#name: JSON Validation
#
#on:
#  pull_request:
#    paths:
#      - '**.json'
#      - '!**/lang/**'
#
#jobs:
#  validate:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup Python
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10' 
#
#      - name: Install dependencies
#        run: pip install jsonschema
#
#      - name: Validate JSON files
#        run: python validate_json.py
#