name: Validate JSON and check ModConfigs

on:
  pull_request:
    paths:
      - 'ModConfigs/**/**/*.json'

jobs:
  validate_json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Validate JSON files
        run: npm run validate-json

  check_modconfigs:
    name: Check ModConfigs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Check ModConfigs
        run: npm run check-modconfigs
