name: json-formatter

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  check-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for JSON files
        run: |
          json_files=$(git diff --name-only HEAD~1 | grep '.json$')
          if [ -n "$json_files" ]; then
            echo "JSON files detected in PR:"
            echo "$json_files"
            exit 1
          fi

      - name: Check object parameters
        run: |
          for file in $(git diff --name-only HEAD~1 | grep '.json$'); do
            first_object_params=$(jq -r '.[0] | length' "$file")
            if [ "$first_object_params" -ne 4 ]; then
              echo "File $file has first object with $first_object_params parameters instead of 4."
              exit 1
            fi
          done
