name: Validate JSON

on:
  pull_request:
    paths:
      - 'ModConfigs/**/**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install -g ajv-cli

    - name: Validate JSON
      run: |
          if git diff --name-only HEAD $(echo $GITHUB_BASE_REF) -- | grep -q 'ModConfigs/' && \
              git diff --name-only HEAD $(echo $GITHUB_BASE_REF) -- | grep -q '\.json$' && \
              jq -e 'if .mods and .desc and .name and .authors then true else false end' \
              $(git diff --name-only HEAD $(echo $GITHUB_BASE_REF) -- | grep 'ModConfigs/' | grep '\.json$') >/dev/null 2>&1; then
            echo "The JSON files are valid and contain the required parameters."
          else
            echo "The JSON files are invalid or missing required parameters."
            exit 1
          fi