name: Auto update
on:
  push:
    paths:
      - "ModConfigs/**"
    
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Index
        run: |
          root_url="https://{root}"
          mods=""
          for file in $(find ModConfigs -name '*.json'); do
            name=$(basename $(dirname $file))
            version=$(basename $(dirname $(dirname $file)))
            url="${root_url}/$file"
            mods+="{ \"name\": \"$name\", \"version\": \"$version\", \"url\": \"$url\" },"
          done
          index="{ \"root\": \"$root_url\", \"mods\": [ ${mods%,} ] }"
          echo $index > ModConfigs/index.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update index.json
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_options: '--no-verify'
          commit_author: GitHub Action <action@github.com>
          file_pattern: ModConfigs/index.json

  send-update:
    needs: update-index
    runs-on: ubuntu-20.04

    steps:
      - name: Send update
        run: wget -O- https://vpdl.nvoid.me/update
